table 'AdventureWorks Customer Lookup'
	lineageTag: 983f4057-9e7d-4b47-ae48-ce2406b5162b

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 4d1ff12e-72c7-4356-9569-c328ccf7e774
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column Prefix
		dataType: string
		lineageTag: 12b727c8-bc3a-4269-a957-8f85a9b8d5f5
		summarizeBy: none
		sourceColumn: Prefix

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 4602b32f-e37c-4996-bb31-276d8317ec68
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: dcbb84c8-e15e-4ff2-8e0c-df02d3903547
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 633b174d-1d17-4613-bf6b-71262a1fd146
		summarizeBy: none
		sourceColumn: BirthDate

		variation Variation
			isDefault
			relationship: 5bca475c-14cc-4a12-976f-242e8d677268
			defaultHierarchy: LocalDateTable_3e886049-412c-43c7-a6af-8225243bd41b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: 72ac42cc-21ab-4aca-828c-b0dd3bed7c9d
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 7ce7b1c4-3f4a-427c-aa0a-ac9987fe2ee9
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 9299fddd-f13d-42fe-bd48-c5b141166223
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column AnnualIncome
		dataType: int64
		formatString: 0
		lineageTag: 484d7b9e-3d01-47c1-a600-668f003c4b4a
		summarizeBy: sum
		sourceColumn: AnnualIncome

		annotation SummarizationSetBy = Automatic

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: dd0101d7-e05d-4882-93eb-5f3282c27209
		summarizeBy: sum
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column EducationLevel
		dataType: string
		lineageTag: b03f0dc2-16f8-4f64-bc7e-6b78bb21c7b6
		summarizeBy: none
		sourceColumn: EducationLevel

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: ea4f1c23-af1d-42e5-bb9b-f57c29dd0a4a
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column HomeOwner
		dataType: string
		lineageTag: eb561882-abcb-4927-bcd0-0c470d17870a
		summarizeBy: none
		sourceColumn: HomeOwner

		annotation SummarizationSetBy = Automatic

	partition 'AdventureWorks Customer Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\sunita.n\Downloads\AdventureWorks Customer Lookup.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"Prefix", type text}, {"FirstName", type text}, {"LastName", type text}, {"BirthDate", type date}, {"MaritalStatus", type text}, {"Gender", type text}, {"EmailAddress", type text}, {"AnnualIncome", Int64.Type}, {"TotalChildren", Int64.Type}, {"EducationLevel", type text}, {"Occupation", type text}, {"HomeOwner", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

